config/routes.rb
Bookery::Application.routes.draw do
  root 'pages#home'

  get 'register', to: 'users#new'
  resources :users, only: [:create, :delete]

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  resources :books do
    get :search, to: 'books#search', on: :collection
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :email, :password
  validates_uniqueness_of :email

  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user
  end

  def require_user
    unless signed_in?
      flash[:error] = 'You are not allowed to do that.'
      redirect_to sign_in_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # redirect_to books_path if signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if signed_in?  
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      flash[:success] = 'Signed in successfully.'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = 'Email address / Password incorrect.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = 'You have been sigend out successfully.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # if signed in not show the registration
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = 'User created successfully.'
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!5
%html(lang='en-US')
  %head
    %title Bookery
    %meta(charset='UTF-8')
    %meta(name='viewport' content='width=device-width, initial-scale=1.0')
    = csrf_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
  %body
    = render 'shared/header'
    .container.margins
      = render 'shared/messages'
      = yield
    %footer.navbar-fixed-bottom.text-center
      %hr
      &copy 2017 - Bookery by 
      %span #{link_to 'KURUSU', '#', class: 'pendiente'}

app/views/pages/home.html.haml
.jumbotron
  %h1.text-center BooKur
  %hr
  .row
    .col-sm-4
      %p BookUr is introducing a place to whom loves to keep an order with all his/her books and search for them pretty easy.
    .col-sm-4
      %p A Little Free Library is a “take a book, return a book” free book exchange. They come in many shapes and sizes, but the most common version is a small wooden box of books. Anyone may take a book or bring a book to share.
    .col-sm-4
      %p Little Free Library is a registered nonprofit organization that inspires a love of reading, builds community, and sparks creativity by fostering neighborhood book exchanges around the world. To learn more about us and how this worldwide movement got started
  
  %hr
  - unless signed_in?
    %p.text-center
      = link_to 'Sign In »', sign_in_path, class: 'btn btn-primary btn-lg'

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button(type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar')
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand myself' do
        %i.fa.fa-book.fa-fw
    .collapse.navbar-collapse#navbar
      %ul.nav.navbar-nav
        %li
          = link_to 'Info', '#'
        - if signed_in?
          %li.dropdown.add_book 
            = link_to '', { class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'true'} do
              Books
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to '' do
                  %i.fa.fa-book
                  Add Book
              %li
                = link_to '' do
                  %i.fa.fa-pencil
                  Add Author
              %li
                = link_to '' do
                  %i.fa.fa-tag
                  Add Category
          = bootstrap_form_tag url: search_books_path, html: { class: 'col-md-5 navbar-form form-search' }, method: :get do |f| 
            .input-group
              = f.search_field :search_term, hide_label: true, placeholder: 'Search for books here...'
              .input-group-btn
                %button(class="btn btn-primary" type="submit")
                  %i.glyphicon.glyphicon-search
        - unless signed_in?
          %li.active
            = link_to 'Register', register_path
      %ul.nav.navbar-nav.navbar-right
        - if signed_in?
          %li.dropdown
            = link_to '', { class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'true' } do
              Welcome, #{current_user.name}
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to '' do
                  %i.fa.fa-user
                  Profile Account
              %li
                = link_to '' do
                  %i.fa.fa-user-plus
                  Edit profile
              %li.divider(role='separator')
              %li
                = link_to sign_out_path, method: :delete do
                  %i.fa.fa-arrow-circle-left
                  Sign out
        - else
          %li= link_to 'Welcome, Free Reader', sign_in_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - name = 'danger' if name == 'error'
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/users/new.html.haml
.jumbotron
  .row
    .col-md-8.col-md-offset-1
      = bootstrap_form_for @user, html: { class: 'form-horizontal' } do |f|
        .col-md-offset-3
          %header
            %h2.text-center Registration
            %hr
          %fieldset
            .row
              .col-md-4
                = f.label :name, 'Full Name:', class: 'control-label'
              .col-md-8
                = f.text_field :name, hide_label: true, placeholder: 'Federico de Asis', icon: 'user'
            .row
              .col-md-4
                = f.label :email, 'Email Address:', class: 'control-label'
              .col-md-8
                = f.email_field :email, hide_label: true, placeholder: 'example@example.com', icon: 'envelope'
            .row
              .col-md-4
                = f.label :password, 'Password', class: 'control-label'
              .col-md-8
                = f.password_field :password, hide_label: true, placeholder: '********', icon: 'eye-close', help: 'Must be 8 characters at least.'
          %fieldset
            .row
              .col-md-offset-4
                = f.submit 'Register', class: 'btn btn-primary'
                %small= "or #{link_to 'Sign in', sign_in_path}".html_safe
%hr